# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  - group: 'VARIABLE-GROUP'
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'


steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'custom'
    custom: 'tool'
    arguments: 'install --global azuresigntool'
  displayName: Install AzureSignTool
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
- task: CmdLine@2
  inputs:
    script: AzureSignTool sign -kvu "https://ssl-com-poc.vault.azure.net/" -kvi "$(66e7b3a6-7a27-4914-99d5-a6db17000a81)" -kvs "$(Sxd8Q~Vj5LXjFBCxhTmUQn9xKZOvO9mX6d~_Na_D)" -kvc test-certificate1 -tr "http://ts.ssl.com" -td sha256 "FILE-TO-SIGN"
  displayName: Sign Code
